### PR TITLE
Prepare 1.0 release

### PR DESCRIPTION
**Pull request by smarr**
After about 9 years of working on ReBench, it seems time to prepare a 1.0 release.

With the changes since the [last release](https://github.com/smarr/ReBench/compare/v0.10.1...HEAD), I have been cleaning up a lot of inconsistency and old cruft.

The two main changes are the UI, i.e., the output on the command line, and the configuration format.
And, we got now documentation: http://rebench.readthedocs.io/

The UI is now hopefully easier to read, more intuitive, and less repetitive, even in debug and verbose mode.
This is achieved by a more structured output and logic to avoid repetition.

The configuration format is overhauled to have a more consistent terminology and use a schema to get better error messages in case a file is not valid.
This means unfortunately that old configuration files are incompatible.

As part of these preparations, I'd love to get some feedback, proof-reading of the docs etc.
So, everyone who I am aware of having used ReBench before, perhaps you guys could have a look:  @charig, @daumayr, @krono, @lhoste-bell, @lschuetze, @theseion, @richard-roberts, @spilot.

Note, there are no changes in this PR, this is mostly to track the release.
The changes are already merged on master (there is currently no PyPI release, but an installation should be as simple as `pip install git+https://github.com/smarr/ReBench`), and the [docs](http://rebench.readthedocs.io/) are available online, too.

PRs, comments on commits or PRs, and any other feedback welcome.

### CODE REVIEW

**Comment by krono** [comment]
Just for meta, consider https://zenodo.org/ for this repo so we can have a DOI for rebench, easier to cite. Rest i'll read later.

**Comment by smarr** [comment]
@krono there is already, though since the DOI changes with each release, I didn't want to put the badge in the README yet: [DOI](https://zenodo.org/badge/latestdoi/1263079)

**Comment by krono** [comment]
ok, never mind then. I was in a hurry.

**Comment by smarr** [comment]
:) When checking for the badge, I saw that there is a stable DOI as well. Might make sense to advertise the one instead of the latest. While that would remove the version info, it would mean that I do not need to update the README after I created a tag and pushed that. Hmm...

**Comment by krono** [comment]
otherwise, looks good from here.

**Comment by smarr** [comment]
@krono thanks for having a look!

**Comment by charig** [comment]
Many thanks for all this work Stefan! Rebench has been very useful to me.

I read the docs, they were quite of for me. For the future, I'd change the term *virtual machine* for something more general because rebench can be used for benchmarking any kind of system I guess.

**Comment by smarr** [comment]
Yeah, we could change it to *executable* perhaps? That's a term I used in the docs already in some places.

Or anything more generic/self-explanatory? Perhaps something that indicates that it is actually a combination of executable and parameters. *executor* maybe? Not sure, sounds  little strange.

**Comment by charig** [comment]
Maybe this is a known todo... if I install the head of the repo using `pip install .` I can not use rebench because schema.yml is not being copied to the installed dir. Copying it by hand solves the issue. I do not create a PR because I am not sure what is the proper way to update the setup.py to do so.

**Comment by smarr** [comment]
@charig Hm, I can't reproduce:

- corrected `.travis.yml` https://github.com/smarr/ReBench/commit/7d5f87a0ef83f2c875902e41195dd36cbbfa8d56
- Travis run: https://travis-ci.org/smarr/ReBench/jobs/404973675#L663 (and also https://travis-ci.org/smarr/ReBench/builds/404973674)

What's the `head` of the repo? The master branch?
That's what is tested on travis.
Any other conditions that may play into this?

**Comment by charig** [comment]
Yes, the `head` of the repo is the last commit of the master branch for me. 
From what I see travis is not running rebench.

I am not in the lab so I can try to reproduce it tomorrow. The steps I remember: 

1. Remove everything from rebench in the pip install directory.
2. `pip install .`.
3.  Run rebench with any config file.

*For step 1 in my case pip uninstall was not enough, I had to remove the dir manually.*

**Comment by smarr** [comment]
@charig thanks. hopefully fixed with #94.

**Comment by charig** [comment]
I do not see how the *iterations* variable works right now. According to the documentation: 
`The number of times a run is executed within a virtual machine invocation. This needs to be supported by a benchmark harness and ReBench passes this value on to the harness or benchmark.`
However, I set the iterations globally and also per benchmark but I could not find a way to pass that value to the application. I would expect something like ReBench automatically appending this value to the running command. 
Moreover, since iy was not working I then try using it as a variable inside a command. But it also fails: `'iteration' is not supported as key. Only benchmark, input, variable, cores, and warmup are supported.`. 

So, is it a bug or am I missing something? In the last case, maybe it would be good to improve the corresponding documentation.

**Comment by theseion** [comment]
In the concepts section to define "virtual machines" but in the main section (index.md) you use the term "binaries". I think you should stick with "binaries", as not every program used to produce output has to be a virtual machine. I'll put that change in a PR.

**Comment by smarr** [comment]
@theseion thanks for having a look. I am not sure "binaries" is the best term.

Perhaps, we could use *executable* as a term? That's a term I used in the docs already in some places.

Or anything more generic/self-explanatory? Perhaps something that indicates that it is actually a combination of executable and parameters. *executor* maybe? Not sure, sounds  little strange.

(previously considered in https://github.com/smarr/ReBench/pull/89#issuecomment-405187334)

**Comment by smarr** [comment]
Ok, I am just seeing the edit.

Yes, a VM is a binary+path and arguments. So, it is not just a binary.

Currently, *executor* seems like the least worst option. Any other suggestions?

**Comment by theseion** [comment]
So far I've seen "binary", "executable", "virtual machine" and "executor". I also think that "executor" is the best word. And I'd use "executable" instead of "binary" (e.g. for the case of a shell script, which is executed by a binary but is itself not one).

**Comment by krono** [comment]
Just to give two other names (but those are probably rubbish)

 - “sub” for system-under-benchmark
 - “benchmarkee”

**Comment by theseion** [comment]
Nice suggestions, but I'm not a fan ;)

I've opened #99.

**Comment by smarr** [comment]
With https://github.com/smarr/ReBench/commit/5f2efe78596d624971fdcf2511bb2653615230a3, I released the first release candidate: https://github.com/smarr/ReBench/releases/tag/v1.0rc1
It includes all current changes and everything discussed here.

I'll use it for a while before making the final release.
Until then #105, adding a preferred citation and a list of papers ReBench was used for are the only things left.

**Comment by smarr** [comment]
Thanks a lot everyone!

Took too long, but it's time to declare this version `1.0.0`.   🍾 🥳

**Comment by lschuetze** [comment]
Oh, god. Glad you managed to release it. Just saw that you mentioned me almost 2 years ago. What a shame. Went completely unnoticed to me.

**Pull request merged**
