### PR TITLE
Pass through doc; renamed 'virtual machine' and 'binary'

### PR DESCRIPTION
**Pull request by theseion**
This PR edits the docs/readme, and improves the terminology.

VMs are renamed to exectuors.
Binaries are renamed to executables.

The `vm:` filter on the command line is replaced by `e:` (for executor).

### CODE REVIEW

**Comment by smarr** [comment]
Sorry, I am behind on a lot of things.
Thanks a lot for this change and all the edits!
Still need to process them though.

**Comment by smarr** [comment]
@theseion could tick the checkbox that maintainers can push changes? Then I can simply update the PR with a few more changes.

Thanks!

**Comment by theseion** [comment]
I had done that one I opened the PR. The checkbox to the right ("Allow edits from maintainers") is presented as ticked.

**Comment by smarr** [comment]
If I would read error messages... Thanks!

**Pull request merged**
