### PR TITLE
Add preferred citation and some papers using ReBench

### PR DESCRIPTION
**Pull request by smarr**
This adds a preferred citation and some papers.

@charig @krono @theseion in case you got papers, you'd like to be listed, let me know. See list below.

### CODE REVIEW

**Comment by theseion** [comment]
```[Improving live debugging of concurrent threads through thread histories](https://doi.org/10.1016/j.scico.2017.10.005), M. Leske, A. Chiş, O. Nierstrasz```

**Comment by krono** [comment]
```markdown
[Adaptive Just-in-time Value Class Optimization for Lowering Memory Consumption and Improving Execution Time Performance](https://doi.org/10.1016/j.scico.2016.08.003.) T. Pape, C. F. Bolz, R. Hirschfeld [[pdf]](https://arxiv.org/pdf/1606.06726)

[Pycket: a tracing JIT for a functional language](https://doi.org/10.1145/2784731.2784740), S. Bauman, C. F. Bolz, R. Hirschfeld, V. Kirilichev, T. Pape, J. G. Siek, S. Tobin-Hochstadt [[pdf]](https://www.hpi.uni-potsdam.de/hirschfeld/publications/media/BaumanBolzHirschfeldKirilichevPapeSiekTobinHochstadt_2015_PycketATracingJitForAFunctionalLanguage_AcmDL.pdf)

[Adaptive just-in-time value class optimization: transparent data structure inlining for fast execution](https://doi.org/10.1145/2695664.2695837), T. Pape, C. F. Bolz, R. Hirschfeld [[pdf]](http://hpi.uni-potsdam.de/hirschfeld/publications/media/PapeBolzHirschfeld_2015_AdaptiveJustInTimeValueClassOptimization_AcmDL.pdf)

[Meta-tracing makes a fast Racket](https://pdfs.semanticscholar.org/333e/a43ab30ae453d6bd847360cd475275e0acbf.pdf), C. F. Bolz, T. Pape, J. Siek, S. Tobin-Hochstadt
```

**Comment by charig** [comment]
Thanks!

Maybe:

[Building efficient and highly run-time adaptable virtual machines](https://doi.org/10.1145/2989225.2989234), G. Chari, D. Garbervetsky, S. Marr

**Comment by smarr** [comment]
Great, thank you guys, added them to the list (slightly adapted to have a consistent style).

**Comment by krono** [comment]
(but why et.al.?)

**Comment by smarr** [comment]
@krono To avoid having to list everyone? Was already considering cutting the authors completely to keep things clean and simple. Would like avoid unnecessary clutter in the README.

**Comment by smarr** [comment]
Note, I also added a basic `AUTHORs.md` to give credit to @daumayr @charig @theseion @krono.

**Comment by krono** [comment]
My gut feeling would be better no authors than et.al. but it's up to you :)

**Pull request merged**
