### PR TITLE
fixes issue #60

### PR DESCRIPTION
**Pull request by theseion**
* use math.floor() to round time units when printing time left

### CODE REVIEW

**Comment by smarr** [comment]
Ha, ok, didn't think of that. I suppose that's a proper fix :)

But, it looks like you stole one closing parenthesis (line 184 I think). Travis ain't happy.
If you could fix that, I'll merge.

Thanks!

**Comment by theseion** [comment]
Oops! Fixed.

**Comment by smarr** [comment]
Thanks! I took the liberty to squash and reword the commit message though.

**Comment by theseion** [comment]
You're welcome.

**Pull request merged**
